apiVersion: apps/v1
kind: Deployment
metadata:
  name: vosk
spec:
  selector:
    matchLabels:
      app: vosk
  template:
    metadata:
      labels:
        app: vosk
        app.kubernetes.io/name: vosk
    spec:
      containers:
        - name: vosk
          image: alphacep/kaldi-ru:latest
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: vosk-service
spec:
  selector:
    app: vosk
    app.kubernetes.io/name: vosk
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005